
{% set name = "das2py" %}
{% set version = "2.3.1" %}
{% set bld_date = "20191107" %}
{% set sha256 = "a417f1f5bbb5af408cbf3ced8c2da007ed40964f3d0468e6f6f4af95e865ab48" %}


package:
   name: {{ name }} 
   version: {{ version }} 
   
source:
   fn:  libdas2.3-{{ version }}.tar.gz
   url: http://das2.org/das2py/files/libdas2.3-{{ bld_date }}.tar.gz
   sha256: {{ sha256 }}
   
   
build:
   # This is the zeroth build
   number: 0
   
# The build process for das2py calls python in the make files so we
# need to make sure it uses the anaconda python, not the system version

requirements:
   build:
      - {{ compiler('c') }}
            
   host:
      - python
      - setuptools
      - cython
      - numpy >=1.10.4 
      - numpy-devel >=1.10.4
      - expat
      - fftw
      - zlib
      - openssl
      - pthreads4w [win]
      
   run:
      - python
      - setuptools
      - cython
      - numpy >=1.10.4 
      - numpy-devel >=1.10.4
      - expat
      - fftw
      - zlib
      - openssl
      - pthreads4w [win]
      
test:
   imports:
      - das2
      - _das2

about:
   home: https://das2.org/das2py
   license: MIT
   license_file: bindings/python/LICENSE
   summary: An efficient space physics data client for python
